UNIT NOITE ;//ATENCAO NOME DA UNIT = NOME DO ARQUIVO QUE A CONTEM
//=================================================================
//A PRINCIPIO, UMA UNIDADE CONTERA UMA BIBLIOTECA DE MODULOS (FUNCTIO/PROCEDURE)
//
INTERFACE
  PROCEDURE LEIA(OQUELER:STRING[30];VAR NUM:INTEGER);
  PROCEDURE VALDATAP(DD,MM,AA:INTEGER;VAR CHAVE:BOOLEAN);
  FUNCTION DIAMAXM(MM,AA:INTEGER):INTEGER;
  FUNCTION VALDATAF(DD,MM,AA:INTEGER):BOOLEAN;
  PROCEDURE TERMINE;
//===========================================================================
IMPLEMENTATION
PROCEDURE TERMINE; //PARA ENCERRAR O PROGRAMA
BEGIN
 WRITE('ENTER PARA ENCERRAR');
 READLN;
END;
//
//===========================================================================
//
PROCEDURE LEIA(OQUELER:STRING[30];VAR NUM:INTEGER);
//PROCEDIMENTO QUE LE DO TECLADO STRING E DEVOLVE UM INTEIRO
 VAR NUSS:STRING[20];
     ER:INTEGER;
BEGIN
 REPEAT
  WRITE(OQUELER); //OQUE CONTEM A FRASE INDICANDO O QUE EH PARA DIGITAR
  READLN(NUSS);    //LE COMO STRING
  VAL(NUSS,NUM,ER);
  IF(ER<>0)THEN
   WRITELN('CARACTER NAO NUMERICO');
 UNTIL(ER=0);
END;
//
//===========================================================================
//
FUNCTION DIAMAXM(MM,AA:INTEGER):INTEGER;
//FUNCAO QUE RECEBE MEs E ANO E DEVOLVE O NUMERO MAXIMO DE DIAS DO MES
  VAR DMMES:INTEGER;
	 BEGIN
	  DMMES:=31;
		IF(MM=4) OR (MM=6) OR (MM=9) OR (MM=11) THEN
		 DMMES:=30;
		IF(MM=2)THEN
		 BEGIN
		  DMMES:=28;
			IF((AA MOD 4) = 0)THEN
			 DMMES:=29;
		 END;
	 DIAMAXM:=DMMES;
END;
//==================================================
FUNCTION VALDATAF(DD,MM,AA:INTEGER):BOOLEAN;
//FUCAO QUE
//RECEBE DIA MES E ANO E DEVOLVE TRUE OR FALSE EM FUNCAO DA DATA SER VALIDA OU INVALIDA
{	INICIO DA FUNCAO}
VAR DMMES:INTEGER;// POIS ESTOU USANDO O RESULTADO DA FUNCTION DIRETO
    CHAVE:BOOLEAN;
Begin
 CHAVE:=TRUE;
//COME�A A VALIDAR A DATA LIDA, A PARTIR DO ANO
//CONSIDERAR ANOS MENORES QUE 1940 E MAIORES QUE 2010 INVALIDA
 IF(AA<1940) OR (AA >2024) THEN
  CHAVE:=FALSE
 ELSE
//SE ANO OK, VALIDA O MES
  IF(MM<1) OR (MM>12)THEN
	 CHAVE:=FALSE
	ELSE
//VERIFICA O DIA
//PARA VERIFICAR O DIA TENHO QUE SABER O NUMERO MAXIMO DE DIAS DO MES LIDO
   BEGIN
		DMMES:=DIAMAXM(MM,AA);
		IF(DD<1) OR (DD>DIAMAXM(MM,AA))THEN
		 CHAVE:=FALSE;
  VALDATAF:=CHAVE;
	 END;
END;
{FIM DA FUNCAO}
//==============================================================
PROCEDURE VALDATAP(DD,MM,AA:INTEGER;VAR CHAVE:BOOLEAN);
//PROCEDIMENTO QUE
//RECEBE DIA MES E ANO E DEVOLVE TRUE OR FALSE EM FUNCAO DA DATA SER VALIDA OU INVALIDA,
//NO PARAMETRO PASSADO POR REFERENCIA  RES
{	INICIO DO PROCEDURE}
VAR DMMES:INTEGER;
Begin
 CHAVE:=TRUE;
//COME�A A VALIDAR A DATA LIDA, A PARTIR DO ANO
//CONSIDERAR ANOS MENORES QUE 1940 E MAIORES QUE 2010 INVALIDA
 IF(AA<1940) OR (AA >2024) THEN
  CHAVE:=FALSE
 ELSE
//SE ANO OK, VALIDA O MES
  IF(MM<1) OR (MM>12)THEN
	 CHAVE:=FALSE
	ELSE
//VERIFICA O DIA
//PARA VERIFICAR O DIA TENHO QUE SABER O NUMERO MAXIMO DE DIAS DO MES LIDO
   BEGIN
		DMMES:=DIAMAXM(MM,AA);
		IF(DD<1) OR (DD>DMMES)THEN
		 CHAVE:=FALSE;
 	 END;
END;
//===================================================================
END.